Bug fixes for international Degrees & GCSEs
DFE-Digital/apply-for-teacher-training pull request #2967
Opened 2020-09-22 14:06 UTC by davidgisbey

## Context

There are a few bugs at the moment in the international degrees section. This PR tackles two separate cards and two additional bugs that i noticed when fixing the first two.

## Changes proposed in this pull request

Both the degree and gcse review component

1. The review components for international degrees/gcses should NOT show the comparable UK qualification row if they selected they did not have a NARIC reference number

Degrees - NARIC page

1. Show 'Not provided' as the value on the NARIC reference number row if the candidate chose not to provide one
2. Prefill the form correctly so the 'No' radio button works correctly
3. If a candidate has added a NARIC reference number. Then chooses to change their response to 'No' it sets the naric_reference and comparable_uk_degree to nil (previously it retained their previous values).
 
## Guidance to review

Test it locally/on the review app 👍 

## Link to Trello card

https://trello.com/c/0QxX0k6r/2052-%F0%9F%8C%90-comparable-uk-degree-shown-in-summary-card-for-international-degree-if-answered-no-to-having-a-naric-statement
https://trello.com/c/ojQCw0IY/2056-%F0%9F%8C%90-empty-naric-ref-field-in-summary-when-no-naric-equivalent-for-degree

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

2020-09-22 15:02 UTC, paulrobertlloyd commented
Not quite right on the review page, need to show either 3 lines relating to NARIC, or one:

No NARIC statement:

<img width="979" alt="Screenshot 2020-09-22 at 15 59 56" src="https://user-images.githubusercontent.com/813383/93900113-ec96ab00-fcec-11ea-9413-e45b6fbc8d49.png">

Has NARIC statement:

<img width="982" alt="Screenshot 2020-09-22 at 16 01 14" src="https://user-images.githubusercontent.com/813383/93900124-eef90500-fcec-11ea-81b1-daa2aa34650a.png">

Also, I think we should be consistent and say `NARIC`, not `UK NARIC`. Do you agree @EmmaFrith?

2020-09-23 10:10 UTC, EmmaFrith commented
> Also, I think we should be consistent and say `NARIC`, not `UK NARIC`. Do you agree @EmmaFrith?

yup agree @paulrobertlloyd

2020-09-23 13:23 UTC, tvararu approved these changes

2020-09-23 13:50 UTC, paulrobertlloyd requested changes
Just a typo to fix, then 🚢

2020-09-23 13:50 UTC, paulrobertlloyd commented on app/components/candidate_interface/gcse_qualification_review_component.rb
> +        key: 'Do you have a NARIC statment of comparability?',
```suggestion
        key: 'Do you have a NARIC statement of comparability?',
```

Sorry, this was my spelling mistake!

2020-09-23 13:50 UTC, paulrobertlloyd commented on config/locales/application_form.yml
> +        review_label: Do you have a NARIC statment of comparability?
```suggestion
        review_label: Do you have a NARIC statement of comparability?
```

Ditto.

2020-09-23 14:15 UTC, merged