Request a referee flow part5 - Review unsubmitted reference page
DFE-Digital/apply-for-teacher-training pull request #3094
Opened 2020-10-08 17:23 UTC by davidgisbey

## Context

## Changes proposed in this pull request

## Guidance to review

## Link to Trello card

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

2020-10-08 22:26 UTC, stevehook approved these changes
Tested locally and worked for me. Code looks good.

2020-10-09 09:13 UTC, malcolmbaig requested changes
LG, one thing to double check

2020-10-09 09:13 UTC, malcolmbaig commented on app/controllers/candidate_interface/decoupled_references/review_controller.rb
> +              Reference::RefereeTypeForm.build_from_reference(@reference).valid?
`EmailForm` instead?

2020-10-09 09:15 UTC, davidgisbey commented on app/controllers/candidate_interface/decoupled_references/review_controller.rb
> +              Reference::RefereeTypeForm.build_from_reference(@reference).valid?
👍 good spot. Theo has requested that these forms are refactored into one form (RefereeForm) so these this should not be quite such a horror show after the next PR.

2020-10-09 09:20 UTC, paulrobertlloyd commented on app/views/candidate_interface/decoupled_references/email_address/_shared_form.html.erb
> +        sandbox feature
```suggestion
        Sandbox feature
```

2020-10-09 09:48 UTC, malcolmbaig approved these changes

2020-10-09 10:54 UTC, malcolmbaig commented
Couple of typos in commit message https://github.com/DFE-Digital/apply-for-teacher-training/pull/3094/commits/443546683cb925f73fae930a104094729033cc8d

2020-10-09 13:52 UTC, tvararu approved these changes

2020-10-09 20:23 UTC, merged