Only allow sign-ups from education.gov.uk emails addresses on qa etc.
DFE-Digital/apply-for-teacher-training pull request #3372
Opened 2020-11-09 17:34 UTC by stevehook

## Context

We want to restrict use of test environments (qa, review apps and staging) to DfE uses (those with `education.gov.uk` email addresses).

## Changes proposed in this pull request

- [x] `HostEnvironment.dfe_signups_only?` helper
- [x] Add validation to the `SignUpForm` to prevent non-DfE sign-ups depending on environment.
- [x] System spec
- [ ] General warning to candidates and pointer to production environment.

![image](https://user-images.githubusercontent.com/450843/98575986-cb484900-22b1-11eb-8c5f-3bea0935e65d.png)

## Guidance to review

- Does the validation make sense?
- Is the copy for the validation error correct?
- What is the best UX for pointing candidates to the production environment?

## Link to Trello card

https://trello.com/c/M1IWxq2c/2481-only-allow-digitaleducationgovuk-signups-on-qa-staging-review-apps

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

2020-11-10 12:40 UTC, tvararu approved these changes
I think this is good enough, maybe @paulrobertlloyd can suggest further improvements :+1:

2020-11-10 12:42 UTC, paulrobertlloyd commented
@tvararu Chatted with @stevehook, going to redirect to a page that gives error message, and allows linking to the production environment (which is not possible with an error summary)

2020-11-11 11:42 UTC, paulrobertlloyd commented
@stevehook Can we add a back link to the error page?

2020-11-11 12:03 UTC, stevehook commented
> @stevehook Can we add a back link to the error page?

thanks @paulrobertlloyd I missed that, done now

2020-11-11 17:23 UTC, paulrobertlloyd commented on app/views/candidate_interface/sign_up/external_sign_up_forbidden.html.erb
> +    </h2>
```suggestion
    <h1 class="govuk-heading-xl">
      <%= t('page_titles.external_sign_up_forbidden') %>
    </h1>
```

2020-11-11 17:24 UTC, paulrobertlloyd requested changes
Just one tiny change. Otherwise LGTM!

2020-11-11 23:50 UTC, paulrobertlloyd approved these changes

2020-11-12 08:46 UTC, merged