Add ability to edit candidate addresses
DFE-Digital/apply-for-teacher-training pull request #3674
Opened 2020-12-17 10:33 UTC by raamSoftwire

## Context

We are increasing the support UI to enable support users to make changes more easily. This PR looks add editing address details.

## Changes proposed in this pull request

![image](https://user-images.githubusercontent.com/33458055/102476023-7f2bb980-4052-11eb-9472-3c7bb6b655fe.png)

![image](https://user-images.githubusercontent.com/33458055/102476044-8783f480-4052-11eb-9e4d-c94695722ed5.png)

![image](https://user-images.githubusercontent.com/33458055/102476074-95397a00-4052-11eb-86cb-a9cf58cc99a4.png)

![image](https://user-images.githubusercontent.com/33458055/102476114-a08ca580-4052-11eb-8b10-c31aa8b93ee2.png)

![image](https://user-images.githubusercontent.com/33458055/102476183-b4d0a280-4052-11eb-929c-ee56e683e8fb.png)

![image](https://user-images.githubusercontent.com/33458055/102476219-c0bc6480-4052-11eb-82da-cfd696e83bf1.png)

## Guidance to review

@stevehook is currently working on refactoring international addresses. We will build on his work to offer both new and old forms on the international address details page to help support users migrate old addresses to the new format.

I've borrowed a lot from the existing flow in the candidate interface. It might be worth peeking at the `contact_details_form` and the associated system and form specs.

## Link to Trello card

https://trello.com/c/LrAuSaZs/2687-expand-the-personal-details-review-section-in-the-support-ui-address-incl-international

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

2020-12-17 12:30 UTC, george-bit requested changes
LGTM only minor name changes.

2020-12-17 12:30 UTC, george-bit commented on spec/system/support_interface/editing_address_details_spec.rb
> +  scenario 'Support user edits reference', with_audited: true do
```suggestion
  scenario 'Support user edits address', with_audited: true do
```

2020-12-17 12:30 UTC, george-bit commented on spec/system/support_interface/editing_address_details_spec.rb
> +RSpec.feature 'Editing reference' do
```suggestion
RSpec.feature 'Editing address' do
```

2020-12-17 13:42 UTC, george-bit approved these changes
👍

2020-12-17 15:02 UTC, stevehook approved these changes
Review app works really nicely.

My only thoughts were about the duplication of things like validations between forms in the candidate and support interfaces. I like the idea of having separate forms for separate interfaces and often they will be very different but I'd be interested in others thoughts on whether it's something we should try to DRY a bit and if so how best to go about it. In any case we should iterate on that in future (and we'll have to add the new international address structure here soon anyway).

2020-12-17 15:27 UTC, raamSoftwire commented
@malcolmbaig has done a similar PR (https://github.com/DFE-Digital/apply-for-teacher-training/pull/3670) and there are a few refactors I want to implement here before merging.

2020-12-17 18:05 UTC, raamSoftwire commented on app/controllers/support_interface/application_forms/address_details_controller.rb
> +          address_details_params.merge(address_type: @application_form.address_type),
@malcolmbaig after our chat I decided to go for the approach already taken on the Candidate side.

I think this is more explicit about passing in the extra `address_type` param, and allows us to stick to the pattern of using `Form.new` in the update action.

2020-12-17 18:13 UTC, raamSoftwire commented on spec/forms/support_interface/application_forms/edit_address_details_form_spec.rb
> +        address_line1: Faker::Address.street_name,
We already have other calls to `Faker::Address.street_name` in the codebase. Do we currently see this causing issues? 

If we did then it looks like [we can specify a max length](https://github.com/faker-ruby/faker/issues/249#issuecomment-54014800).

2020-12-17 18:13 UTC, raamSoftwire commented
> @malcolmbaig has done a similar PR (#3670) and there are a few refactors I want to implement here before merging.

I've pushed those refactors now.

2020-12-18 09:00 UTC, raamSoftwire commented
> Review app works really nicely.
> 
> My only thoughts were about the duplication of things like validations between forms in the candidate and support interfaces. I like the idea of having separate forms for separate interfaces and often they will be very different but I'd be interested in others thoughts on whether it's something we should try to DRY a bit and if so how best to go about it. In any case we should iterate on that in future (and we'll have to add the new international address structure here soon anyway).

I think this is a good point that we should think about. I did feel a little uneasy with the amount of copy and pasting. But I saw it as necessary within the namespaced approach we've taken. I had a good conversation with @malcolmbaig about it and he suggested we be guided by the [Rule of Three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)). I think this sounds about right to me but maybe also something to discuss with the other devs at the next dev retro/near miss session.

2020-12-18 09:26 UTC, merged