Add location codes to 'Apply with UCAS' page
DFE-Digital/apply-for-teacher-training pull request #4040
Opened 2021-02-10 11:56 UTC by malcolmbaig

## Context
Candidates see this page when arriving from Find and applying for a
course through UCAS. This change provides additional location info in
the form of a sites table underneath the provider and course code.

## Changes proposed in this pull request

- Make sites for a given course available by adding a new ActiveRecord
  association to the Course model.
- Fetch sites data from the API when dealing with an unsynced course.
- Augment the FindAPI::Site model with methods that match the interface
  of the Site model.
- Render a table with name, address, and code information.
## Guidance to review
- Review diff
- Test locally or on a review app, viewing the following:
    - A synced course that's available on Apply
    - A synced course that's not available on Apply
    - An unsynced course (if possible)

## Link to Trello card

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/docs/environment-variables.md#azure-hosting-devops-pipeline)

2021-02-10 11:57 UTC, malcolmbaig commented
@stevehook This PR is closely related to https://trello.com/c/ErVvUSIA

2021-02-10 12:12 UTC, paulrobertlloyd commented on app/views/candidate_interface/apply_from_find/apply_on_ucas_only.html.erb
> +      <%= t('page_titles.apply_from_find_with_ucas') %>
Ultimately we’ll want to adjust page heading sizes down from `xl` to `l`, but I think we should do that in one go in a separate PR.

```suggestion
    <h1 class="govuk-heading-xl">
      <span class="govuk-caption-xl"><%= @course.name_and_code %></span>
      <%= t('page_titles.apply_from_find_with_ucas') %>
```

2021-02-10 12:31 UTC, paulrobertlloyd requested changes
Few lil things…

2021-02-10 12:31 UTC, paulrobertlloyd commented on app/views/candidate_interface/apply_from_find/apply_on_ucas_only.html.erb
> +      Visit Get Into Teaching for <a class="govuk-link" target="_blank" href="https://beta-getintoteaching.education.gov.uk/steps-to-become-a-teacher#step-5">guidance on applying for teacher training
Should we use `govuk_link_to` helper here?

2021-02-10 12:31 UTC, paulrobertlloyd commented on app/views/candidate_interface/apply_from_find/apply_on_ucas_only.html.erb
> +      <table class="govuk-table app-table--vertical-align-middle" data-qa='locations-table'>
```suggestion
      <table class="govuk-table app-table--vertical-align-middle" data-qa="locations-table">
```

2021-02-10 14:50 UTC, davidgisbey commented on app/models/find_api/site.rb
> +    end
Hey, we're moving away from using the v3 API. Can we use this instead please:

![image](https://user-images.githubusercontent.com/42515961/107526070-5ede2e00-6baf-11eb-863d-c9c13186b38f.png)

2021-02-10 14:54 UTC, davidgisbey commented on app/models/find_api/site.rb
> +    end
We're moving away from using the V3 API where possible. Please can we use the public API for this? So TeacherTrainingPublicAPI::Location

2021-02-11 09:42 UTC, stevehook commented
> @stevehook This PR is closely related to https://trello.com/c/ErVvUSIA

thanks @malcolmbaig, there's a lot in common with my card, so probably makes sense to wait for this to get merged first. Other than David's suggestion it looks like it's ready to go.

2021-02-11 15:09 UTC, davidgisbey approved these changes
As discussed, i think you're right. We should continue to use the FindAPI until the has many sites discussion is resolved on the public API.

Happy to ship this when you drop the wip commit.

Sorry for causing you the extra work!

2021-02-11 16:04 UTC, stevehook approved these changes
:+1:

2021-02-12 09:55 UTC, merged