[WIP] Display vacancy status on course selection
DFE-Digital/apply-for-teacher-training pull request #4704
Opened 2021-05-10 18:49 UTC by JR-G

## Context

## Changes proposed in this pull request

## Guidance to review

## Link to Trello card

https://trello.com/c/rgEO3WLn/2133-display-vacancy-status-and-ucas-only-when-prompting-candidates-for-course

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] This code does not rely on the addition/removal of Azure config environment variables in the same Pull Request
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/docs/environment-variables.md#azure-hosting-devops-pipeline)

2021-05-11 15:03 UTC, stevehook reviewed
Looks good - just a few comments related to the perf thing we were discussing on Slack.

2021-05-11 15:03 UTC, stevehook commented on app/forms/candidate_interface/pick_course_form.rb
> +        courses = courses_for_current_cycle.exposed_in_find.includes(:accredited_provider, :course_options)
The alternative to using `includes` is to move the logic into the DB query with a join and condition on the joined table:
`courses_for_current_cycle.joins(:course_options).where('course_options.available': true).distinct`
the problem is that that doesn't return the ones that aren't available, so you would need two queries. But if performance is a still a problem that's probably the next thing to try.

2021-05-11 15:31 UTC, JR-G commented on app/forms/candidate_interface/pick_course_form.rb
> +        courses = courses_for_current_cycle.exposed_in_find.includes(:accredited_provider, :course_options)
I've updated `radio_available_courses` and it seems to be performing better on the review app

2021-05-11 16:07 UTC, paulrobertlloyd commented
Wondering if we can display courses as follows:

* Without age range:
  `Music (X123) – No vacancies`
* With age range:
  `Music, 11 to 16 (X124) – No vacancies`

2021-05-12 09:50 UTC, JR-G commented
> Wondering if we can display courses as follows:
> 
> * Without age range:
>   `Music (X123) – No vacancies`
> * With age range:
>   `Music, 11 to 16 (X124) – No vacancies`

@paulrobertlloyd There are some courses that will display an additional description: `English (456) – PGCE with QTS full time - No vacancies`. Shall I follow a similar pattern in reducing the number of hyphens?

2021-05-12 09:57 UTC, paulrobertlloyd commented
How about this…

Select option (only shows qualification when disambiguating):

```
Music, 11 to 16 (X124) – PGCE with QTS full time – No vacancies
```

Radio option (shows qualification as hint text):

```
* Music, 11 to 16 (X124) – No vacancies
  PGCE with QTS full time
```

2021-05-13 08:27 UTC, frankieroberto approved these changes

2021-05-13 08:42 UTC, paulrobertlloyd commented on app/forms/candidate_interface/pick_course_form.rb
> +            name += ' - Only on UCAS'
```suggestion
            name += ' – Only on UCAS'
```

2021-05-13 08:42 UTC, paulrobertlloyd commented on app/forms/candidate_interface/pick_course_form.rb
> +            name += ' - No vacancies'
```suggestion
            name += ' – No vacancies'
```

2021-05-13 08:43 UTC, paulrobertlloyd commented on app/views/candidate_interface/course_choices/course_selection/new.html.erb
> +              <%= f.govuk_radio_button :course_id, course.id, label: { text: "#{course.name} (#{course.code}) - Only on UCAS" }, hint: { text: course.description }, link_errors: i.zero? %>
```suggestion
              <%= f.govuk_radio_button :course_id, course.id, label: { text: "#{course.name} (#{course.code}) – Only on UCAS" }, hint: { text: course.description }, link_errors: i.zero? %>
```

2021-05-13 08:43 UTC, paulrobertlloyd commented on app/views/candidate_interface/course_choices/course_selection/new.html.erb
> +              <%= f.govuk_radio_button :course_id, course.id, label: { text: "#{course.name} (#{course.code}) - No vacancies" }, hint: { text: course.description }, link_errors: i.zero? %>
```suggestion
              <%= f.govuk_radio_button :course_id, course.id, label: { text: "#{course.name} (#{course.code}) – No vacancies" }, hint: { text: course.description }, link_errors: i.zero? %>
```

2021-05-13 08:48 UTC, paulrobertlloyd commented on spec/forms/candidate_interface/pick_course_form_spec.rb
> +      expect(form.dropdown_available_courses.map(&:name)).to eql(['English (456) – PGCE with QTS full time - No vacancies', 'English (789) – PGCE full time - No vacancies', 'Maths (123)'])
```suggestion
      expect(form.dropdown_available_courses.map(&:name)).to eql(['English (456) – PGCE with QTS full time – No vacancies', 'English (789) – PGCE full time – No vacancies', 'Maths (123)'])
```

2021-05-13 08:49 UTC, paulrobertlloyd commented on spec/system/candidate_interface/course_selection/candidate_selecting_a_course_that_is_full_spec.rb
> +    expect(page).to have_text("#{@course.name_and_code} - No vacancies")
```suggestion
    expect(page).to have_text("#{@course.name_and_code} – No vacancies")
```

2021-05-13 08:50 UTC, paulrobertlloyd requested changes
Just need to use an [en-dash](https://en.wikipedia.org/wiki/Dash#En_dash) not a hyphen for separating words.

2021-05-13 08:58 UTC, davidgisbey approved these changes
lgtm once the change have been amde

2021-05-13 12:26 UTC, paulrobertlloyd approved these changes

2021-05-13 12:44 UTC, merged