Support interface revert a rejection
DFE-Digital/apply-for-teacher-training pull request #4724
Opened 2021-05-13 09:01 UTC by stevehook

## Context

## Changes proposed in this pull request

## Guidance to review

WIP

## Link to Trello card

https://trello.com/c/LPKMNuUN/3361-add-functionality-to-the-support-ui-to-revert-a-rejection

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] This code does not rely on the addition/removal of Azure config environment variables in the same Pull Request
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/docs/environment-variables.md#azure-hosting-devops-pipeline)

2021-05-17 15:57 UTC, malcolmbaig commented on spec/system/support_interface/revert_rejection_spec.rb
> +  scenario 'View structured reasons for rejection', with_audited: true do
nit: worth correcting the scenario here so the commit makes sense in isolation (can see it's corrected later on)

2021-05-17 16:00 UTC, malcolmbaig commented on spec/components/support_interface/application_choice_component_spec.rb
> +    it 'Does not renders a link to the revert rejection page when application was rejected by default' do
typo: renders

2021-05-17 16:09 UTC, malcolmbaig commented on spec/services/support_interface/revert_rejection_spec.rb
> +end
Quite liked the testing pattern used [here](https://github.com/DFE-Digital/apply-for-teacher-training/pull/4572/files#diff-6e3f92ab4664c6b3c021cb2511b292d4a484c9c4acec2bde45f3ba7f1dfda083) where DeclineOffer is used to make the state change and we expect equality between the original choice and the updated one. Would it make sense to do similar here?

2021-05-17 16:13 UTC, malcolmbaig approved these changes
Code looks good, and works as expected in review app. A few minor comments left inline. Maybe needs a designer to take a look as well.

2021-05-20 08:53 UTC, paulrobertlloyd commented on app/views/support_interface/application_forms/application_choices/confirm_revert_rejection.html.erb
> +        <li>it was rejected within 5 working days of the request to revert and,</li>
```suggestion
        <li>it was rejected within 5 working days of the request to revert</li>
```

2021-05-20 08:57 UTC, paulrobertlloyd commented on app/views/support_interface/application_forms/application_choices/confirm_revert_rejection.html.erb
> +                text: 'Zendesk ticket URL',
Given we are using the same label (and hint) value for auditing changes like this, should we localise these strings to me this a bit DRYer?

2021-05-20 08:57 UTC, paulrobertlloyd requested changes
Just a few small things.

2021-05-20 12:40 UTC, stevehook commented
> Oh, I was thinking all occurrences use one set of strings? Is that a good idea?

I wasn't sure about this. There is a school of thought that says that duplication in i18n files is ok because different things in different contexts may need different content. But I don't think that applies here so I've moved them all to more a generic key.

2021-05-20 14:19 UTC, paulrobertlloyd approved these changes

2021-05-21 09:50 UTC, merged