Update application data export headings and labels
DFE-Digital/apply-for-teacher-training pull request #6302
Opened 2022-01-05 16:01 UTC by JR-G

## Context

The form input headings and labels are incorrect in the "Export application data" report.

## Changes proposed in this pull request

- [x] Changed "Select year" to "Recruitment cycle"
- [x] Changed "Select applications" to "Status"
- [x] Changed "All applications" to "All statuses"
- [x] Changed "Applications with a specific status" to "Specific statuses"
- [x] Changed the checkbox group heading in the conditional reveal from "Selected statuses" to "Status"

## Guidance to review

## Link to Trello card

https://trello.com/c/jmsW9V2p

## Things to check

- [x] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

2022-01-05 16:53 UTC, simonwhatley commented
There are a couple of additional changes needed:

- Change “Select applications for certain organisations” to “Organisation”
- Order organisations alphabetically

2022-01-06 09:24 UTC, simonwhatley requested changes

2022-01-06 09:24 UTC, simonwhatley commented on app/views/provider_interface/application_data_export/new.html.erb
> +        <%= f.govuk_collection_check_boxes :provider_ids, @application_data_export_form.providers_that_actor_belongs_to.order('name ASC'), ->(p) { p.id.to_s }, :name, legend: { text: 'Organisations',
```suggestion
        <%= f.govuk_collection_check_boxes :provider_ids, @application_data_export_form.providers_that_actor_belongs_to.order('name ASC'), ->(p) { p.id.to_s }, :name, legend: { text: 'Organisation', size: 'm' } %>
```

2022-01-06 09:31 UTC, cwrw approved these changes

2022-01-06 09:33 UTC, simonwhatley approved these changes

2022-01-06 09:40 UTC, merged