4399 dev apply again content changes
DFE-Digital/apply-for-teacher-training pull request #6545
Opened 2022-02-15 16:48 UTC by avinhurry

## Context

## Changes proposed in this pull request

## Guidance to review

## Link to Trello card

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

2022-02-16 18:30 UTC, EmmaFrith commented
In the application_rejected_all_applications_rejected_after_apply2_deadline email, can we change:

'Your last application has been saved. Make any changes and re-submit from 6:28pm on 23 February 2022.'

To:

Your last application is saved. All you need to do is:

- make any changes
- choose up to 3 courses
- submit

I must've missed this one from the audit @avinhurry

2022-02-16 18:32 UTC, EmmaFrith commented on app/views/candidate_mailer/_still_interested_content.text.erb
> +  - Choose up to 3 courses
```suggestion
  - choose up to 3 courses
```

2022-02-16 18:32 UTC, EmmaFrith commented on app/views/candidate_mailer/_still_interested_content.text.erb
> +  - Submit
```suggestion
  - submit
```

2022-02-16 18:39 UTC, EmmaFrith commented
On the 'application_submitted_apply_again' mailer, does 'training provider' pluralise if they submit more than one application?: 

'If your training provider decides to progress your application, they’ll contact you to organise an interview.'

If there's more than one course, are the courses listed in bullet points as in the Apply 1 email?

2022-02-16 18:57 UTC, EmmaFrith commented
are we doing the terms of use changes in this PR too @avinhurry?

2022-02-16 18:58 UTC, EmmaFrith requested changes
Thanks @avinhurry, it's looking great. I've added some questions and suggestions.

2022-02-16 21:55 UTC, avinhurry commented
> Your last application is saved. All you need to do is:
> 
>     * make any changes
> 
>     * choose up to 3 courses
> 
>     * submit from [time] on [date]

This was changed, it just doesn't show in the preview because there's a conditional in the email template. It has to be between a certain time period for this to show. I'll attach a screenshot here. It just doesn't have the time and the date on the third bullet... 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/50492247/154363898-5791b3bd-31c2-4db0-99a6-052866dbedab.png">

2022-02-16 21:59 UTC, avinhurry commented on app/views/candidate_mailer/_still_interested_content.text.erb
> +  - Make any changes
oops, I did ask about this and you did say, sorry 😞

Changes made

2022-02-16 21:59 UTC, avinhurry commented on app/views/candidate_mailer/_still_interested_content.text.erb
> +  - Choose up to 3 courses
same here

2022-02-16 21:59 UTC, avinhurry commented on app/views/candidate_mailer/_still_interested_content.text.erb
> +  - Submit
and here

2022-02-16 22:14 UTC, avinhurry commented
> On the 'application_submitted_apply_again' mailer, does 'training provider' pluralise if they submit more than one application?:
> 
> 'If your training provider decides to progress your application, they’ll contact you to organise an interview.'
> 
> If there's more than one course, are the courses listed in bullet points as in the Apply 1 email? @avinhurry

If the `apply_again_with_three_choices` feature flag is active, the `application_submitted` email is sent, once we delete the feature flag we will delete the `application_submitted_apply_again` email template because it won't be used.

2022-02-16 22:17 UTC, avinhurry commented
> are we doing the terms of use changes in this PR too @avinhurry?

You mean this file, right? `terms_candidate.md` Yes i've updated it - it's in this PR.

2022-02-17 10:15 UTC, EmmaFrith commented
@avinhurry could you change this sentence

![Screenshot 2022-02-17 at 10 14 40](https://user-images.githubusercontent.com/56349171/154454855-87548077-f1d0-4354-9046-c220d2bb78d4.png)

to:

You can apply **again** if your initial application does not lead to a place.

2022-02-17 11:42 UTC, stevehook approved these changes
This all makes sense to me, good stuff! I can't see any references to the `apply_again_call_to_action` email. And it was a one-off so there shouldn't be any jobs for it left in the Sidekiq queue.

2022-02-17 12:55 UTC, EmmaFrith approved these changes
LGTM. Thanks Avin!

2022-02-17 14:17 UTC, merged