672 add reinstate references service
DFE-Digital/apply-for-teacher-training pull request #7515
Opened 2022-10-03 15:34 UTC by tomas-stefano

## Context

There were a couple of cards in support of providers accidentally marking applications as not met or candidates accidentally being withdrawn. At the moment, its easy to reverse but if we cancel the outstanding references when we call these services we would need to manually re-add the references.

We add the service, just in case anyone needs to reinstate any reference via support ticket.

2022-10-04 08:54 UTC, elliotcm requested changes

2022-10-04 08:54 UTC, elliotcm commented on docs/support_playbook.md
> +```
```suggestion
### Reinstate a reference

When an application ends up in an unsuccessful state we change the outstanding
references to "cancelled".

If we need to reinstate a reference we have a service called
ReinstateReference which will revert the reference from 'cancelled' to
'feedback_request' and will send an email to the referee.

```
  ReinstateReference.new(reference, audit_comment: 'zen-desk ticket url').call
```
```

2022-10-04 08:54 UTC, elliotcm commented on docs/support_playbook.md
> +```
Just a lil wording change

2022-10-04 08:57 UTC, elliotcm requested changes

2022-10-04 08:57 UTC, elliotcm commented on docs/support_playbook.md
> +'feedback_request' and will send an email to the referee as well.
```suggestion
When an application ends up in an unsuccessful state we change the outstanding
references to "cancelled".

If we need to reinstate a reference we have a service called
ReinstateReference which will revert the reference from 'cancelled' to
'feedback_request' and will send an email to the referee.
```

Lil wording change.

2022-10-04 09:19 UTC, carlosmartinez commented on docs/support_playbook.md
> +When an application endup in an unsuccessful state we change the outstanding
endup -> ends up

2022-10-04 09:20 UTC, carlosmartinez approved these changes

2022-10-04 10:26 UTC, JonF1 approved these changes

2022-10-07 13:14 UTC, elliotcm approved these changes

2022-10-07 13:51 UTC, merged