755 update the equality and diversity survey
DFE-Digital/apply-for-teacher-training pull request #7577
Opened 2022-10-14 09:13 UTC by tomas-stefano

## Context

Update the Equality and diversity survey so that back links and "Continue" buttons take you back to the review screen when changing an answer.

Update the check your answers page in our HESA questionnaire (to not use brackets)

2022-10-17 08:41 UTC, carlosmartinez commented on app/controllers/candidate_interface/equality_and_diversity_controller.rb
> +          redirect_to candidate_interface_edit_equality_and_diversity_ethnic_background_path(params[:return_to].present? ? params.slice(:return_to) : nil)
does `params.fetch(:return_to, nil)` do the job?

2022-10-17 08:57 UTC, frankieroberto requested changes
I'm getting a 500 error when clicking 'Change ethnicity' and then pressing the Continue button.

When clicking 'Change' on any of the answers, the 'Back' link should take you back to the Check your answers page.

2022-10-17 16:29 UTC, frankieroberto requested changes
Tested in review app. Back links are working now when used after changing an answer.

2 minor amends please:

* change "Disability" to "Disabilities or health conditions" on Check your answers page
* If someone selects "I do not have any of these disabilities or health conditions", display that exact text on the Check your answers page instead of "No".

2022-10-18 10:40 UTC, carlosmartinez approved these changes

2022-10-19 11:26 UTC, JonF1 approved these changes

2022-10-20 14:58 UTC, tomas-stefano commented on app/controllers/candidate_interface/equality_and_diversity_controller.rb
> +    def review_back_link
Done ♻️

2022-10-21 08:51 UTC, frankieroberto approved these changes

2022-10-21 13:06 UTC, merged