Add failed gcse information
DFE-Digital/apply-for-teacher-training pull request #7727
Opened 2022-11-22 09:10 UTC by tomas-stefano

## Context

[Edit](https://trello.com/c/wjaFJo7C/770-surface-additional-gcse-information-in-the-support-interface#)
If a candidate does not have a GCSE A to C (or 4 or above) in English, Maths and Science, we ask them some follow-up question to see whether they are retaking their GCSE, or if they have any other evidence of meeting the GCSE requirement.

We should update the Support interface to surface this information.

2022-11-22 09:11 UTC, tomas-stefano commented
![](https://github.trello.services/images/mini-trello-icon.png) [Surface additional GCSE information in the support interface](https://trello.com/c/wjaFJo7C/770-surface-additional-gcse-information-in-the-support-interface)

2022-11-22 15:30 UTC, carlosmartinez approved these changes

2022-11-23 09:49 UTC, frankieroberto commented
@tomas-stefano just tested this in the review app, and this is how it appears:

<img width="1212" alt="Screenshot 2022-11-23 at 09 41 42" src="https://user-images.githubusercontent.com/30665/203514734-062d0228-8563-4a15-ace6-c8f9d5c4e857.png">

Looks good good me. One minor issue is that the "Other evidence I have the skills required" question should only be shown if the candidate does not have the GCSE C or above _and_ is not currently retaking the qualification. This is because if they ARE currently retaking a GCSE, they're not asked the question:

<img width="1041" alt="Screenshot 2022-11-23 at 09 42 20" src="https://user-images.githubusercontent.com/30665/203515335-b1508ddb-e2ba-4ddc-ac73-26d008a9384f.png">

If a candidate says they don't have the GCSE or equivalent qualification, but are currently studying for one, then I think instead of "Reason given" the label should be something like "Details of qualification currently studying for" - to match the question asked on the candidate side:

<img width="882" alt="Screenshot 2022-11-23 at 09 47 09" src="https://user-images.githubusercontent.com/30665/203515935-0e09e79c-240f-448e-9943-cb51d2d33f62.png">

If a candidate says they don't have the GCSE or equivalent qualification, and aren't currently studying for one, but gives evidence of meeting the skills, then I think the label should be "Other evidence of skills required" instead of "Reason given", to match the candidate interface and the other answers.

Happy to talk this through - and let's get this update on the provider interface too (if they don't share the same partials?).

2022-11-24 10:34 UTC, frankieroberto requested changes

2022-11-24 10:34 UTC, frankieroberto commented on app/components/shared/gcse_qualification_cards_component.html.erb
>                <dd class="app-qualification__value"><%= qualification.not_completed_explanation || qualification.missing_explanation %></dd>
This label needs to be conditional upon whether the candidate answered "Yes" or "No" to "Are you currently studying for this qualification?"

If they answered Yes, and then completed the free text, then the label should be "Details of qualification currently studying for". If they answered No, and then fill out the "If you have other evidence of having maths skills at the required standard, give details (optional)" then we should display "Other evidence I have the skills required" with their answer.

Currently this field can be mis-labelled:

<img width="378" alt="Screenshot 2022-11-24 at 10 31 48" src="https://user-images.githubusercontent.com/30665/203761916-ebe5dadf-f125-420e-b0ba-708421a363b8.png">

Hope that makes sense?

2022-11-24 10:34 UTC, frankieroberto commented on spec/components/utility/gcse_qualification_cards_component_spec.rb
> +    context 'when failed required gcse' do
Small tweak just to make clear that "D" isn't a "fail", but just below the ITT standard.

```suggestion
    context 'when their GCSE grade is below C or 4' do
```

2022-11-30 11:48 UTC, frankieroberto requested changes
Re-tested in review app.

Looks good. One last change. Where the candidate does not have the qualification and is not currently studying for it, and does not enter anything in the "Other evidence..." box (ie it's blank) can we add the text "Not provided"? Otherwise it looks a bit odd:

<img width="370" alt="Screenshot 2022-11-30 at 11 46 25" src="https://user-images.githubusercontent.com/30665/204788331-4fee0462-9aa2-4ad2-8c76-aec498520521.png">

2022-11-30 13:24 UTC, frankieroberto approved these changes

2022-11-30 14:17 UTC, merged