Don't break page if GCSE doesn't have a grade
DFE-Digital/apply-for-teacher-training pull request #7988
Opened 2023-02-28 11:50 UTC by carlosmartinez

## Context

Currently it's not possible for a provider or support user to view an application with a GCSE that doesn't have a grade or constituent_grades; they see a 500 error.

## Changes proposed in this pull request

Instead of erroring, fail gracefully-ish with a warning message.

## Guidance to review

- Update an application to have a science GCSE with `grade: nil, constituent_grades: nil`
- Attempt to access that application in the support console
- Let the good times roll

## Link to Trello card

https://trello.com/c/NBDcyF3b/1204-it-shouldnt-be-possible-for-candidates-to-enter-a-gcse-science-without-grade-or-constituent-grades

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

2023-02-28 15:46 UTC, JR-G approved these changes

2023-03-01 09:46 UTC, frankieroberto requested changes
Do we know how/why this has happened?

2023-03-01 09:46 UTC, frankieroberto commented on app/components/shared/gcse_qualification_cards_component.html.erb
> +                </div>
I don't think we need to use the warning text here. A simple message styled the same as the rest, and using a `<dd>` element, should be fine (and more accessible)?

```suggestion
                    <dd class="app-qualification__value">Not added</dd>
```

2023-03-01 10:13 UTC, carlosmartinez commented
> Do we know how/why this has happened?

In the Bad Old Days, it seems we were missing a validation.

2023-03-01 13:29 UTC, frankieroberto approved these changes

2023-03-01 13:30 UTC, frankieroberto commented
> > Do we know how/why this has happened?
> 
> In the Bad Old Days, it seems we were missing a validation.

😞  Does it affect any current (awaiting decision) applications? 🤞

2023-03-06 09:54 UTC, merged