Fix Master's and PhD grade options
DFE-Digital/apply-for-teacher-training pull request #8167
Opened 2023-04-19 08:24 UTC by stevehook

## Context

When we prompt users to enter a grade for a Master's or PhD degree we are presenting the option for Bachelors degrees. This PR corrects that by presenting Master's specific grades for Master's degrees and skipping the grade step entirely for PhDs.

## Changes proposed in this pull request

- New systems specs to cover entry of Master's and PhDs.
- Special case for Master's degrees surfaces these options:

![image](https://user-images.githubusercontent.com/450843/233014800-f111d9b8-b14a-4e44-9ec3-cf3cff249b95.png)

- Special case for PhDs in `DegreeWizard` to skip the grade step and set the value to `'Pass'`.

## Guidance to review

- Are the tests sufficient here?
- Are there any other cases I'm missing?

## Link to Trello card

[
](https://trello.com/c/z5XTrOIw/875-fix-our-masters-and-phd-grade-options-that-broke-during-our-new-degree-flow)

## Things to check

- [x] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [x] API release notes have been updated if necessary
- [x] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

2023-04-20 11:30 UTC, tomas-stefano approved these changes
After the tests are fixed and @frankieroberto take a look on the design 🚀

2023-04-20 15:51 UTC, frankieroberto requested changes
Tested in review app.

One minor bug: if you add a PhD/Doctorate it correctly skips the grade question, but it still displays the Grade row in the summary, with "Pass", and clicking change takes you to a page showing the undergraduate degree radios (although selecting anything other than 'Pass' seems to be ignored).

<img width="1011" alt="Screenshot 2023-04-20 at 16 48 17" src="https://user-images.githubusercontent.com/30665/233419780-25412c57-4715-4786-b29a-d174d74aff30.png">

Expected behaviour I think is to not show this row at all when summarising PhD/Doctorate degrees?

2023-04-20 15:51 UTC, frankieroberto commented on app/components/candidate_interface/degree_grade_component.html.erb
>    <%= form.govuk_radio_buttons_fieldset :grade, legend: { text: legend_helper, size: 'l' }, hint: { text: t('application_form.degree.grade.international.grade_examples') } do %>
Can we drop the hint text where there are radios buttons please? The hint text only makes sense where there's a free text box (ie for qualifications equivalent to a degree).

2023-04-21 09:08 UTC, stevehook commented
> Tested in review app.

> One minor bug: if you add a PhD/Doctorate it correctly skips the grade question, but it still displays the Grade row in the summary, with "Pass", and clicking change takes you to a page showing the undergraduate degree radios (although selecting anything other than 'Pass' seems to be ignored).

Thanks @frankieroberto! I've removed the grade row for PhDs only and got rid of that unhelpful hint text.

2023-04-21 09:54 UTC, frankieroberto commented
@stevehook thanks!

The options for Doctorates are a bit weird: <img width="559" alt="Screenshot 2023-04-21 at 10 14 15" src="https://user-images.githubusercontent.com/30665/233597320-785e5294-73cc-4b9b-8908-19fb884cb250.png">

I think it’s meant to look like this, with two "Doctor of Philosophy" options (but with different abbreviations - due to some historical quirk).

<img width="636" alt="Screenshot 2023-04-21 at 10 52 36" src="https://user-images.githubusercontent.com/30665/233606295-085c6b76-9b76-4e54-b2d4-b62adb5206f5.png">

Is this an issue with the upstream data in the reference data gem?

2023-04-21 10:03 UTC, frankieroberto commented
@stevehook thinking about it, I think we should probably use the free text grade option for "Level 6 Diploma" or if the candidate selects "Another qualification equivalent to a degree" too?

<img width="645" alt="Screenshot 2023-04-21 at 11 01 58" src="https://user-images.githubusercontent.com/30665/233608825-c715904f-787a-4e4d-96c7-9b5aa3457fe9.png">

(This could be a follow-up PR though?)

2023-04-21 10:25 UTC, stevehook commented
> The options for Doctorates are a bit weird: 
> I think it’s meant to look like this, with two "Doctor of Philosophy" options (but with different abbreviations - due to some historical quirk).

@frankieroberto the list of options here is hardcoded in Apply so it's easy enough to add the third option (it's available in the reference data gem we just have to add it to our own list).

As for the extra (DPhil) suffix, this is coming from the gem. It adds it for this one case to make the names unique (versus the PhD version of Doctor of Philosophy). I've changed the suffixing logic on our side to only add one if it's not already there to hopefully resolve this.

Let me know what you think...

![image](https://user-images.githubusercontent.com/450843/233613099-5ab12a0e-20a1-4552-8215-17e2a680404c.png)

2023-04-21 11:01 UTC, frankieroberto approved these changes

2023-04-21 14:58 UTC, merged