Introduce Candidate Interface primary navigation
DFE-Digital/apply-for-teacher-training pull request #8311
Opened 2023-06-05 15:26 UTC by inulty-dfe

## Context

This PR implements the new design for a primary navigation bar for the Candidate Interface.

It will allow for navigation items to be added in a convenient and clear place for candidates to navigate the application.

## Changes proposed in this pull request
### Pre offer
- No longer show email address in black header bar
- Move sign out link from black header bar to grey navigation bar, aligned right
- Add "Your application(s)" as the first (and only) navigation item, and show it as selected.

### Post Offer

- Once a candidate accepts an offer = Remove tab called ‘Your applications’ and replace with ‘Your offer’
- On the post offer dashboard change H1 from Your teacher training course’ to “Your offer for [course name e.g. English (Px198)]” - so it matches the tab name
- Keep links on right hand side to view application or withdraw
- If candidate withdraws = Remove tab called “Your offer” and replace with ‘Your applications’ where they can see the withdrawn application along with their others. And that way they can start applying again if needed.

### Screenshots

#### Pre-Offer 

| Before | After |
| --- | --- |
| ![Preoffer-before](https://github.com/DFE-Digital/apply-for-teacher-training/assets/135042929/70369adc-ea5b-448d-8c7a-7bca036baf94) | ![Preoffer-after](https://github.com/DFE-Digital/apply-for-teacher-training/assets/135042929/a867933b-af8d-4cd3-a533-762fa645f5db) |

#### Recruited

| Before | After |
| --- | --- |
| ![Recruited-before](https://github.com/DFE-Digital/apply-for-teacher-training/assets/135042929/4ac540b6-dfb2-4ca2-82b6-1fc22363d012) | ![Recruited-after](https://github.com/DFE-Digital/apply-for-teacher-training/assets/135042929/de92ddac-cc09-4faa-9d01-0b7eb5a92705) |

## Guidance to review
[Review Deployment](https://apply-review-8311.test.teacherservices.cloud/candidate/account)

### Changelog

 > f it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?

Is suspect this change deserves an entry in the changelog. Could someone advise on this please?

## Link to Trello card

https://trello.com/c/Y2XWWTn3/1516-ca-implement-the-candidate-navbar-pre-offer-dashboard
https://trello.com/c/KnoEO8hm/1515-ca-implement-the-candidate-navbar-offer-dashboard

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

2023-06-07 12:44 UTC, frankieroberto requested changes
Tested this Safari and used responsive mode to check mobile size.

Mobile view looks good ✅ :

![Screenshot 2023-06-07 at 13 30 21](https://github.com/DFE-Digital/apply-for-teacher-training/assets/30665/6cf0ded3-a2ee-4caf-8fb6-d9171cbdc48f)

A couple of changes needed:

1. Can you remove the 1px grey border from the bottom of the "phase banner" (with the "review" label) - this no longer needed as the navigation bar acts as a visual boundary. However it'll still need the border on any views which don't have the navigation bar (eg when signed out or the static content pages).

2. The border beneath the black GOVUK header (purple on review apps but blue in production) should also extend to the width of the screen I think, like it already does in the Manage and Support interfaces.

Here’s how it looks in the prototype:

<img width="1126" alt="Screenshot 2023-06-07 at 13 40 34" src="https://github.com/DFE-Digital/apply-for-teacher-training/assets/30665/83c65976-d3ff-42c8-8b5f-73aee397aca1">

Finally, there's a small bug this has introduced with the support navigation bar, which seems to have an extra indent at the start (before "Candidates"):

<img width="1134" alt="Screenshot 2023-06-07 at 13 27 19" src="https://github.com/DFE-Digital/apply-for-teacher-training/assets/30665/fee976ab-b781-4f49-89b7-8cac6b3f8698">

2023-06-07 16:12 UTC, frankieroberto approved these changes
Checked again and looks good to me.

2023-06-07 18:23 UTC, JR-G commented
Just ran through the flow – looks good and is working well! The only comment I have is that when I accepted an offer it's still showing the tab as "Your application" vs "Your offer" I think we want this to change upon accepting an offer @MaeveRoseveare ?
<img width="1025" alt="image" src="https://github.com/DFE-Digital/apply-for-teacher-training/assets/47917431/3f3269e7-de8e-4b6f-a52a-eddb7545b0b1">

2023-06-08 15:59 UTC, JR-G approved these changes

2023-06-08 16:38 UTC, merged